CREATE DATABASE IF NOT EXISTS resumeflow;
USE resumeflow;

CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resumes (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 title VARCHAR(150) NOT NULL,
 summary TEXT,
 template VARCHAR(50) DEFAULT 'classic',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS education (
 id INT AUTO_INCREMENT PRIMARY KEY,
 resume_id INT NOT NULL,
 degree VARCHAR(150),
 institution VARCHAR(150),
 year VARCHAR(20),
 FOREIGN KEY(resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS skills (
 id INT AUTO_INCREMENT PRIMARY KEY,
 resume_id INT NOT NULL,
 skill VARCHAR(100) NOT NULL,
 FOREIGN KEY(resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS experience (
 id INT AUTO_INCREMENT PRIMARY KEY,
 resume_id INT NOT NULL,
 company VARCHAR(150),
 position VARCHAR(150),
 description TEXT,
 FOREIGN KEY(resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projects (
 id INT AUTO_INCREMENT PRIMARY KEY,
 resume_id INT NOT NULL,
 title VARCHAR(150),
 description TEXT,
 FOREIGN KEY(resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);
